"""
Trading signal domain models.

Signals represent trading opportunities detected by strategies.
"""
from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Any, Optional
import uuid


class SignalType(str, Enum):
    """Type of trading signal."""
    BUY_YES = "BUY_YES"
    BUY_NO = "BUY_NO"
    SELL_YES = "SELL_YES"
    SELL_NO = "SELL_NO"
    ARBITRAGE = "ARBITRAGE"  # Buy both YES and NO
    CLOSE_POSITION = "CLOSE_POSITION"


class SignalPriority(str, Enum):
    """Signal urgency/priority level."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"  # Time-sensitive arbitrage


@dataclass
class TradingSignal:
    """A trading signal generated by a strategy."""
    signal_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    strategy_name: str = ""
    market_id: str = ""
    signal_type: SignalType = SignalType.BUY_YES
    confidence: float = 0.0  # 0.0 to 1.0
    priority: SignalPriority = SignalPriority.MEDIUM
    target_size_usd: Decimal = Decimal("0")
    yes_price: Decimal = Decimal("0")
    no_price: Decimal = Decimal("0")
    expected_pnl: Decimal = Decimal("0")
    max_slippage: Decimal = Decimal("0.01")  # 1% default
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.utcnow)
    expires_at: Optional[datetime] = None

    def __post_init__(self) -> None:
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(f"confidence must be between 0 and 1, got {self.confidence}")

    @property
    def combined_price(self) -> Decimal:
        """Get combined price for YES + NO (relevant for arbitrage)."""
        return self.yes_price + self.no_price

    @property
    def is_arbitrage(self) -> bool:
        """Check if this is an arbitrage signal."""
        return self.signal_type == SignalType.ARBITRAGE

    @property
    def is_expired(self) -> bool:
        """Check if signal has expired."""
        if self.expires_at is None:
            return False
        return datetime.utcnow() > self.expires_at


@dataclass
class ApprovedSignal:
    """A signal that has been approved by risk manager."""
    signal: TradingSignal
    approved_size_usd: Decimal
    risk_adjustments: dict[str, Any] = field(default_factory=dict)
    approved_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class RejectedSignal:
    """A signal that was rejected by risk manager."""
    signal: TradingSignal
    rejection_reason: str
    rejected_at: datetime = field(default_factory=datetime.utcnow)
