name: Build and Deploy Mercury

on:
  push:
    branches: [main, master]
    tags: ['v*']
    paths:
      - 'mercury/**'
      - '.gitea/workflows/build.yml'
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to production'
        required: false
        default: 'true'
        type: boolean

env:
  REGISTRY: harbor.server.unarmedpuppy.com
  IMAGE_NAME: library/mercury

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./mercury
          file: ./mercury/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Create deployment artifact
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mkdir -p deploy-artifacts
          cp mercury/docker/docker-compose.prod.yml deploy-artifacts/
          cp mercury/docker/prometheus-prod.yml deploy-artifacts/
          cp mercury/docker/prometheus-alerts.yml deploy-artifacts/
          cp mercury/docker/.env.example deploy-artifacts/
          cp -r mercury/docker/grafana deploy-artifacts/
          cp -r mercury/config deploy-artifacts/

      - name: Upload deployment artifacts
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: mercury-deploy-${{ github.ref_name }}
          path: deploy-artifacts/

  deploy:
    needs: build
    if: |
      startsWith(github.ref, 'refs/tags/v') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'true')
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy notification
        run: |
          echo "Mercury deployment triggered"
          echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}"
          echo ""
          echo "To deploy manually on the server:"
          echo "1. cd /opt/mercury"
          echo "2. MERCURY_VERSION=${{ github.ref_name }} docker compose -f docker-compose.prod.yml pull"
          echo "3. MERCURY_VERSION=${{ github.ref_name }} docker compose -f docker-compose.prod.yml up -d"
