name: Build and Deploy

on:
  push:
    branches: [main, master]
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    uses: unarmedpuppy/workflows/.gitea/workflows/docker-build.yml@main
    with:
      image_name: library/polyjuiced
      app_path: apps/polyjuiced
    secrets: inherit
